services:
  ycsbackend:
    build:
      context: .
    command: yarn start:dev
    restart: always
    working_dir: /app
    env_file: ./.env
    volumes:
      - .:/app
    ports:
      - 3031:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB_NAME: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5449:5432

volumes:
  pg-data:
