-- Custom SQL migration file --
ALTER TABLE comments ADD COLUMN score FLOAT NOT NULL DEFAULT 0,
  ADD COLUMN like_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN dislike_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN reply_count INTEGER NOT NULL DEFAULT 0;